### PR TITLE
New roi tools

### PR DESCRIPTION
**Pull request by JoaoPeriquito**
added ROI tools such as:
- Region growing
- Edge detection
- Dilate
- Erode

### CODE REVIEW

**Comment by plaresmedima** [comment]
Very nice but can you please also update requirements.txt and pyproject.toml please?

**Comment by plaresmedima** [comment]
Bug after clicking erode multiple times

Traceback (most recent call last):
  File "c:\users\steve\dropbox\software\qib-sheffield\wezel\src\wezel\widgets\image_view.py", line 126, in mousePressEvent      
    self.eventHandler.itemMousePressEvent(event)
  File "c:\users\steve\dropbox\software\qib-sheffield\wezel\src\wezel\widgets\mask_view.py", line 782, in itemMousePressEvent   
    im_eroded = cv2.erode(im, kernel)
UnboundLocalError: local variable 'kernel' referenced before assignment

**Comment by JoaoPeriquito** [comment]
The bug was fixed. 

Bug: if "single ROI" mode is selected to erode/dilate and the user does not select an ROI wezel crashes
Solution: if "single ROI" mode is selected to erode/dilate and the user does not select an ROI, all ROIs are dilated or eroded

**Comment by plaresmedima** [comment]
I still seem to have this problem? Could it be?

Traceback (most recent call last):
  File "c:\users\steve\dropbox\software\qib-sheffield\wezel\src\wezel\widgets\image_view.py", line 126, in mousePressEvent
    self.eventHandler.itemMousePressEvent(event)
  File "c:\users\steve\dropbox\software\qib-sheffield\wezel\src\wezel\widgets\mask_view.py", line 782, in itemMousePressEvent
    im_eroded = cv2.erode(im, kernel)
UnboundLocalError: local variable 'kernel' referenced before assignment

**Pull request merged**
